### ISSUE TITLE
Create more than 1 Classroom

### ISSUE THREAD

**Issue by hughdani** [bestlkh/ice-MC2#152]
(locally tested, fails on release works on master) Creating more than one classroom throws an error.

/home/daniel/Desktop/MC2/ice-MC2/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'collection' of undefined
    at /home/daniel/Desktop/MC2/ice-MC2/AdminView/index.js:298:21
    at handleCallback (/home/daniel/Desktop/MC2/ice-MC2/node_modules/mongodb/lib/utils.js:120:56)
    at /home/daniel/Desktop/MC2/ice-MC2/node_modules/mongodb/lib/collection.js:1416:5
    at handleCallback (/home/daniel/Desktop/MC2/ice-MC2/node_modules/mongodb/lib/utils.js:120:56)
    at /home/daniel/Desktop/MC2/ice-MC2/node_modules/mongodb/lib/cursor.js:683:5
    at handleCallback (/home/daniel/Desktop/MC2/ice-MC2/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorNotified (/home/daniel/Desktop/MC2/ice-MC2/node_modules/mongodb-core/lib/cursor.js:515:3)
    at /home/daniel/Desktop/MC2/ice-MC2/node_modules/mongodb-core/lib/cursor.js:597:16
    at queryCallback (/home/daniel/Desktop/MC2/ice-MC2/node_modules/mongodb-core/lib/cursor.js:232:18)
    at /home/daniel/Desktop/MC2/ice-MC2/node_modules/mongodb-core/lib/connection/pool.js:469:18

**Comment by hughdani** [comment]
updating release fixes the issue
